# Generated by Django 5.0.7 on 2026-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_earlyaccessuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(max_length=420)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Adhi', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
