# Generated by Django 5.0.7 on 2026-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pricingsuggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingsuggestion',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='pricingsuggestion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingsuggestion',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
