# Generated by Django 5.0.7 on 2026-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_pricingsuggestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('page_type', models.CharField(choices=[('about', 'About'), ('faq', 'FAQ')], max_length=20)),
                ('excerpt', models.TextField(max_length=420)),
                ('content', models.TextField(help_text='HTML is supported for trusted CMS content.')),
                ('is_published', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('page_type', 'title'),
            },
        ),
    ]
