import json

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils.dateparse import parse_datetime

from apps.core.models import Question, Submission, TestCase, TestCaseResult


QUESTION_FIELDS = [
    "title",
    "description",
    "difficulty",
    "starter_code",
    "java_starter_code",
    "python_starter_code",
    "execution_mode",
    "function_name",
    "is_active",
]

TEST_CASE_FIELDS = [
    "stdin",
    "function_args",
    "expected_value",
    "expected_output",
    "is_sample",
    "is_hidden",
]


def parsed_datetime(value):
    return parse_datetime(value) if value else None


def apply_timestamp(model, instance, created_at=None, updated_at=None):
    updates = {}
    if created_at:
        updates["created_at"] = parsed_datetime(created_at)
    if updated_at:
        updates["updated_at"] = parsed_datetime(updated_at)
    if updates:
        model.objects.filter(pk=instance.pk).update(**updates)


class Command(BaseCommand):
    help = "Import portable code question data and assign imported submissions to a user email."

    def add_arguments(self, parser):
        parser.add_argument("input", help="Path to JSON generated by export_code_data.")
        parser.add_argument("--email", default="adhi@hackerleap.com", help="User email for imported submissions.")
        parser.add_argument(
            "--replace",
            action="store_true",
            help="Delete existing submissions for this email and imported questions before importing submissions.",
        )

    def handle(self, *args, **options):
        input_path = options["input"]
        email = options["email"]

        with open(input_path, "r", encoding="utf-8") as input_file:
            payload = json.load(input_file)

        if payload.get("version") != 1:
            raise CommandError("Unsupported export format. Expected version 1.")

        User = get_user_model()
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist as exc:
            raise CommandError(f"No user exists with email {email!r}. Create the user first, then rerun this command.") from exc
        except User.MultipleObjectsReturned as exc:
            raise CommandError(f"Multiple users exist with email {email!r}. Keep one user or import with a different email.") from exc

        question_payloads = payload.get("questions", [])
        slugs = [question["slug"] for question in question_payloads]

        with transaction.atomic():
            if options["replace"] and slugs:
                Submission.objects.filter(user=user, question__slug__in=slugs).delete()

            imported_questions = 0
            imported_test_cases = 0
            imported_submissions = 0
            imported_results = 0

            for question_payload in question_payloads:
                question_defaults = {field: question_payload[field] for field in QUESTION_FIELDS}
                question, _ = Question.objects.update_or_create(
                    slug=question_payload["slug"],
                    defaults=question_defaults,
                )
                apply_timestamp(
                    Question,
                    question,
                    created_at=question_payload.get("created_at"),
                    updated_at=question_payload.get("updated_at"),
                )
                imported_questions += 1

                test_case_map = {}
                for test_case_payload in question_payload.get("test_cases", []):
                    test_case_defaults = {
                        field: test_case_payload[field]
                        for field in TEST_CASE_FIELDS
                    }
                    test_case_defaults["name"] = test_case_payload.get("name", "")
                    test_case, _ = TestCase.objects.update_or_create(
                        question=question,
                        order=test_case_payload.get("order", 0),
                        name=test_case_payload.get("name", ""),
                        defaults=test_case_defaults,
                    )
                    apply_timestamp(TestCase, test_case, created_at=test_case_payload.get("created_at"))
                    test_case_map[(test_case.name, test_case.order)] = test_case
                    imported_test_cases += 1

                for submission_payload in question_payload.get("submissions", []):
                    submission = Submission.objects.create(
                        user=user,
                        question=question,
                        kind=submission_payload["kind"],
                        language=submission_payload["language"],
                        code=submission_payload["code"],
                        status=submission_payload["status"],
                        stdout=submission_payload.get("stdout", ""),
                        stderr=submission_payload.get("stderr", ""),
                        execution_time_ms=submission_payload.get("execution_time_ms", 0),
                        solve_time_seconds=submission_payload.get("solve_time_seconds"),
                        passed_count=submission_payload.get("passed_count", 0),
                        total_count=submission_payload.get("total_count", 0),
                    )
                    apply_timestamp(Submission, submission, created_at=submission_payload.get("created_at"))
                    imported_submissions += 1

                    for result_payload in submission_payload.get("results", []):
                        test_case_ref = result_payload.get("test_case", {})
                        test_case = test_case_map.get((test_case_ref.get("name", ""), test_case_ref.get("order", 0)))
                        if test_case is None:
                            raise CommandError(
                                "Missing test case for result: "
                                f"{question.slug} / {test_case_ref.get('name', '')} / order {test_case_ref.get('order', 0)}"
                            )
                        TestCaseResult.objects.create(
                            submission=submission,
                            test_case=test_case,
                            status=result_payload["status"],
                            stdout=result_payload.get("stdout", ""),
                            stderr=result_payload.get("stderr", ""),
                            expected_output=result_payload.get("expected_output", ""),
                            execution_time_ms=result_payload.get("execution_time_ms", 0),
                        )
                        imported_results += 1

        self.stdout.write(
            self.style.SUCCESS(
                "Imported "
                f"{imported_questions} questions, "
                f"{imported_test_cases} test cases, "
                f"{imported_submissions} submissions, and "
                f"{imported_results} results for {email}."
            )
        )
