# Generated by Django 5.0.7 on 2026-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='kind',
            field=models.CharField(choices=[('run', 'Run'), ('submit', 'Submit')], default='submit', max_length=20),
        ),
    ]
