# Generated by Django 5.0.7 on 2026-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='solve_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
