# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_submission_solve_time_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.CharField(choices=[("java", "Java 17"), ("python", "Python 3")], default="python", max_length=20),
        ),
    ]
