# Generated by Codex on 2026-06-22

from django.db import migrations, models


JAVA_STARTER = (
    "import java.io.*;\n"
    "import java.util.*;\n\n"
    "public class Main {\n"
    "    public static void main(String[] args) throws Exception {\n"
    "        Scanner scanner = new Scanner(System.in);\n"
    "        int sum = 0;\n"
    "        while (scanner.hasNextInt()) {\n"
    "            sum += scanner.nextInt();\n"
    "        }\n"
    "        System.out.println(sum);\n"
    "    }\n"
    "}\n"
)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_submission_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="starter_code",
            field=models.TextField(default=JAVA_STARTER),
        ),
    ]
