# Generated by Codex on 2026-06-22

from django.db import migrations, models


def infer_existing_submission_languages(apps, schema_editor):
    Submission = apps.get_model("core", "Submission")
    for submission in Submission.objects.all().only("id", "code", "language"):
        code = submission.code or ""
        language = "java" if "class " in code and "public static void main" in code else "python"
        if submission.language != language:
            submission.language = language
            submission.save(update_fields=["language"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_java_starter_default"),
    ]

    operations = [
        migrations.RunPython(infer_existing_submission_languages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.CharField(choices=[("java", "Java 17"), ("python", "Python 3")], default="java", max_length=20),
        ),
    ]
