# Generated by Codex on 2026-06-22

from django.db import migrations, models


JAVA_STARTER_CODE = (
    "import java.io.*;\n"
    "import java.util.*;\n\n"
    "public class Main {\n"
    "    public static void main(String[] args) throws Exception {\n"
    "        Scanner scanner = new Scanner(System.in);\n"
    "        int sum = 0;\n"
    "        while (scanner.hasNextInt()) {\n"
    "            sum += scanner.nextInt();\n"
    "        }\n"
    "        System.out.println(sum);\n"
    "    }\n"
    "}\n"
)

PYTHON_STARTER_CODE = (
    "def solve():\n"
    "    numbers = list(map(int, input().split()))\n"
    "    print(sum(numbers))\n\n\n"
    "if __name__ == \"__main__\":\n"
    "    solve()\n"
)


def looks_like_java(code):
    return "class " in code or "public static void main" in code


def populate_language_starters(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    for question in Question.objects.all().only("id", "starter_code", "java_starter_code", "python_starter_code"):
        starter_code = question.starter_code or ""
        if looks_like_java(starter_code):
            question.java_starter_code = starter_code
            question.python_starter_code = PYTHON_STARTER_CODE
        else:
            question.java_starter_code = JAVA_STARTER_CODE
            question.python_starter_code = starter_code or PYTHON_STARTER_CODE
        question.save(update_fields=["java_starter_code", "python_starter_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_submission_language_default_java"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="java_starter_code",
            field=models.TextField(default=JAVA_STARTER_CODE),
        ),
        migrations.AddField(
            model_name="question",
            name="python_starter_code",
            field=models.TextField(default=PYTHON_STARTER_CODE),
        ),
        migrations.RunPython(populate_language_starters, migrations.RunPython.noop),
    ]
