# Generated by Django 5.0.7 on 2026-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_language_starters'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='execution_mode',
            field=models.CharField(choices=[('stdin', 'Standard input'), ('function', 'Function call')], default='stdin', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='function_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='function_args',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
