# Generated by Django 5.0.7 on 2026-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_submission_user_adminapitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='java_reference_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='python_reference_solution',
            field=models.TextField(blank=True),
        ),
    ]
