# Generated by Codex on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_custom_test_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="questions", to="core.tag"),
        ),
        migrations.CreateModel(
            name="TrackSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("track", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="core.track")),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("track", "title")},
            },
        ),
        migrations.CreateModel(
            name="TrackQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("recommended_time_minutes", models.PositiveIntegerField(default=30)),
                ("pattern_note", models.CharField(blank=True, max_length=240)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="track_entries", to="core.question")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="track_questions", to="core.tracksection")),
            ],
            options={
                "ordering": ["section__order", "order", "id"],
                "unique_together": {("section", "question")},
            },
        ),
    ]
