# Generated by Codex on 2026-07-06

from django.core.management import call_command
from django.db import migrations


def seed_interview_track(apps, schema_editor):
    call_command("seed_interview_track", create_missing=True, verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tags_and_tracks"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
