# Generated by Codex on 2026-07-06

from django.core.management import call_command
from django.db import migrations


def convert_interview_track_to_function_mode(apps, schema_editor):
    call_command("seed_interview_track", create_missing=True, verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_seed_interview_track"),
    ]

    operations = [
        migrations.RunPython(convert_interview_track_to_function_mode, reverse_code=migrations.RunPython.noop),
    ]
