# Generated by Codex on 2026-07-06

from django.core.management import call_command
from django.db import migrations


INTERVIEW_TRACK_SLUG = "interview-preparation"

INTERVIEW_QUESTION_SLUGS = [
    "two-sum",
    "merge-strings-alternately",
    "move-zeroes",
    "is-subsequence",
    "find-pivot-index",
    "unique-number-of-occurrences",
    "valid-parentheses",
    "reverse-linked-list",
    "maximum-depth-of-binary-tree",
    "counting-bits",
    "product-of-array-except-self",
    "group-anagrams",
    "longest-consecutive-sequence",
    "string-compression",
    "container-with-most-water",
    "max-number-of-k-sum-pairs",
    "longest-substring-without-repeating-characters",
    "max-consecutive-ones-iii",
    "longest-subarray-of-1s-after-deleting-one",
    "determine-if-two-strings-are-close",
    "equal-row-and-column-pairs",
    "decode-string",
    "asteroid-collision",
    "daily-temperatures",
    "koko-eating-bananas",
    "search-in-rotated-sorted-array",
    "delete-the-middle-node-of-a-linked-list",
    "odd-even-linked-list",
    "maximum-twin-sum-of-a-linked-list",
    "lru-cache",
    "count-good-nodes-in-binary-tree",
    "path-sum-iii",
    "lowest-common-ancestor-of-a-binary-tree",
    "binary-tree-right-side-view",
    "number-of-provinces",
    "rotting-oranges",
    "course-schedule",
    "kth-largest-element-in-an-array",
    "letter-combinations-of-a-phone-number",
    "house-robber",
    "unique-paths",
    "longest-common-subsequence",
    "implement-trie",
    "non-overlapping-intervals",
    "online-stock-span",
    "trapping-rain-water",
    "minimum-window-substring",
    "sliding-window-maximum",
    "largest-rectangle-in-histogram",
    "edit-distance",
]


def seed_interview_track(apps, schema_editor):
    call_command("seed_interview_track", create_missing=True, verbosity=0)


def hide_interview_track_and_questions(apps, schema_editor):
    Question = apps.get_model("core", "Question")
    Track = apps.get_model("core", "Track")

    Track.objects.filter(slug=INTERVIEW_TRACK_SLUG).update(is_active=False)
    Question.objects.filter(slug__in=INTERVIEW_QUESTION_SLUGS).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_convert_interview_track_to_function_mode"),
    ]

    operations = [
        migrations.RunPython(seed_interview_track, reverse_code=hide_interview_track_and_questions),
    ]
