"""Plain-language statements and visual aids for the interview-preparation track."""


TASKS = {
    "Two Sum": "You are given an array of integers `nums` and an integer `target`. Find two different positions whose values add up to `target`. Return their indices. You may assume exactly one valid pair exists, and you cannot use the same element twice.",
    "Merge Strings Alternately": "You are given two strings. Build a new string by taking one character from `word1`, then one from `word2`, and repeating. If one string is longer, append its remaining characters at the end.",
    "Move Zeroes": "Move every `0` to the end of `nums` while keeping the non-zero values in their original order. Return the updated array.",
    "Is Subsequence": "Return `true` if `s` can be formed by deleting zero or more characters from `t` without changing the order of the remaining characters. Otherwise, return `false`.",
    "Find Pivot Index": "Find an index where the sum of all values strictly to its left equals the sum of all values strictly to its right. Return the leftmost such index, or `-1` if none exists.",
    "Unique Number of Occurrences": "Count how many times each distinct integer appears in `arr`. Return `true` only when no two distinct integers have the same occurrence count.",
    "Valid Parentheses": "The string contains only `(`, `)`, `[`, `]`, `{`, and `}`. Return `true` when every opening bracket is closed by the same bracket type and brackets close in the correct order.",
    "Reverse Linked List": "Reverse the links in the list so the last node becomes the new head. Return the new head. Change the node pointers; do not treat the input as a normal array inside `solve`.",
    "Maximum Depth of Binary Tree": "Return the maximum depth of the binary tree. The depth is the number of nodes on the longest path from the root down to a leaf. An empty tree has depth `0`.",
    "Counting Bits": "For every integer `i` from `0` through `n`, count the number of `1` bits in its binary form. Return an array where position `i` contains that count.",
    "Product of Array Except Self": "Return an array `answer` where `answer[i]` is the product of every value in `nums` except `nums[i]`. Do not use division.",
    "Group Anagrams": "Group together words that use exactly the same letters with the same frequencies. The groups and the words inside each group may be returned in any order.",
    "Longest Consecutive Sequence": "Given an unsorted integer array, return the length of the longest set of consecutive values. The values only need to exist in the array; they do not need to appear next to each other.",
    "String Compression": "Compress each consecutive group of equal characters into the character followed by its count when the count is greater than `1`. Return the compressed string.",
    "Container With Most Water": "Each value in `height` is the height of a vertical line. Choose two lines that form a container with the x-axis. Return the largest amount of water any pair can hold. The container cannot be tilted.",
    "Max Number of K-Sum Pairs": "Repeatedly choose two unused values whose sum is `k` and remove them. Return the largest number of pairs you can make. Each array element can be used at most once.",
    "Longest Substring Without Repeating Characters": "Return the length of the longest contiguous part of `s` that contains no repeated character. A substring must use consecutive characters.",
    "Max Consecutive Ones III": "You may change at most `k` zeroes in the binary array to ones. Return the maximum length of a contiguous block containing only ones after those changes.",
    "Longest Subarray of 1s After Deleting One": "Delete exactly one element from the binary array. Return the length of the longest non-empty contiguous block of ones left afterward. If the array contains only ones, one of them must still be deleted.",
    "Determine if Two Strings Are Close": "You may swap any two characters, and you may replace every occurrence of one existing character with another existing character while swapping those two character groups. Return whether these operations can transform `word1` into `word2`.",
    "Equal Row and Column Pairs": "Count pairs `(row, column)` whose values are exactly equal in the same order. A row and column match only when every position matches.",
    "Decode String": "Decode a string containing patterns of the form `k[encoded]`, which means repeat `encoded` exactly `k` times. Patterns may be nested. Return the fully decoded string.",
    "Asteroid Collision": "Positive asteroids move right and negative asteroids move left. When two moving toward each other meet, the smaller one explodes; equal sizes destroy both. Asteroids moving in the same direction never meet. Return the survivors in their original order.",
    "Daily Temperatures": "For each day, return how many days you must wait for a warmer temperature. Use `0` when no warmer future day exists.",
    "Koko Eating Bananas": "Koko chooses one integer eating speed `k` bananas per hour. During an hour she eats from only one pile, taking up to `k` bananas. Return the smallest speed that lets her finish all piles within `h` hours.",
    "Search in Rotated Sorted Array": "The array was sorted in increasing order and then rotated once. Its values are distinct. Return the index of `target`, or `-1` when it is absent.",
    "Delete the Middle Node of a Linked List": "Delete the middle node and return the list head. For a list of length `n`, the middle node is at zero-based index `floor(n / 2)`. A one-node list becomes empty.",
    "Odd Even Linked List": "Reorder the nodes by their positions: all nodes at odd positions first, followed by all nodes at even positions. Positions start at `1`, and the relative order inside each group must stay the same. Return the head.",
    "Maximum Twin Sum of a Linked List": "The list has an even number of nodes. Node `i` is paired with node `n - 1 - i`. Return the largest sum among all such twin pairs.",
    "LRU Cache": "Process the operations in order using a cache with the given capacity. `get(key)` returns the value or `-1`; `put(key, value)` inserts or updates a key. When a new key exceeds capacity, remove the key that has not been used for the longest time.",
    "Count Good Nodes in Binary Tree": "A node is **good** when no earlier node on the path from the root has a value greater than it. The root is always good. Return the total number of good nodes in the tree.",
    "Path Sum III": "Count all downward paths whose node values add up to `targetSum`. A path may start and end at any nodes, but it must move from parent to child and contain at least one node.",
    "Lowest Common Ancestor of a Binary Tree": "Find the lowest node whose subtree contains both values `p` and `q`. A node may be an ancestor of itself. Return the value stored in that lowest common ancestor.",
    "Binary Tree Right Side View": "Imagine standing to the right of the tree. Return the value of the rightmost visible node at each depth, ordered from top to bottom.",
    "Number of Provinces": "`isConnected[i][j]` is `1` when city `i` and city `j` are directly connected. Connections are also indirect: if A connects to B and B connects to C, all three belong to one province. Return the number of separate provinces.",
    "Rotting Oranges": "Each minute, every rotten orange turns its up, down, left, and right fresh neighbors rotten. Return the number of minutes until no fresh orange remains, or `-1` if some fresh orange can never be reached.",
    "Course Schedule": "There are `numCourses` courses numbered from `0`. Each pair `[course, prerequisite]` means the prerequisite must be completed first. Return whether it is possible to finish every course.",
    "Kth Largest Element in an Array": "Return the `k`th largest value in the array after considering duplicates. It is the `k`th value in descending order, not the `k`th distinct value.",
    "Letter Combinations of a Phone Number": "Each digit from `2` to `9` maps to letters on a telephone keypad. Return every string that can be formed by choosing one letter for each digit. Return an empty list for an empty input. Output order does not matter.",
    "House Robber": "Each value is the money in one house. You cannot rob two adjacent houses because that triggers an alarm. Return the greatest total amount you can rob.",
    "Unique Paths": "A robot starts in the top-left cell of an `m × n` grid and may move only right or down. Return the number of different paths to the bottom-right cell.",
    "Longest Common Subsequence": "A subsequence keeps characters in order but may skip characters. Return the length of the longest subsequence that appears in both `text1` and `text2`.",
    "Implement Trie": "Process `insert`, `search`, and `startsWith` operations on a prefix tree. `search(word)` is true only for a complete inserted word; `startsWith(prefix)` is true when any inserted word begins with that prefix. Return results for the query operations.",
    "Non-overlapping Intervals": "Remove as few intervals as possible so that the remaining intervals do not overlap. Intervals that only touch at an endpoint, such as `[1,2]` and `[2,3]`, do not overlap. Return the number removed.",
    "Online Stock Span": "For each day's stock price, return its span: the number of consecutive days ending today whose price is less than or equal to today's price.",
    "Trapping Rain Water": "The array describes the height of bars of width `1`. After rain, water can remain between taller bars. Return the total number of water units trapped.",
    "Minimum Window Substring": "Return the shortest substring of `s` containing every character from `t`, including repeated characters. Return an empty string when no such window exists. The answer is unique when it exists.",
    "Sliding Window Maximum": "Move a window of size `k` from left to right across `nums`. Return the largest value in each window.",
    "Largest Rectangle in Histogram": "Each bar has width `1` and the given height. Return the largest rectangular area that can be formed using one or more consecutive bars.",
    "Edit Distance": "Return the minimum number of single-character insertions, deletions, and replacements needed to change `word1` into `word2`.",
}


EXPLANATIONS = {
    "Two Sum": "`nums[0] + nums[1] = 2 + 7 = 9`, so return `[0,1]`.",
    "Merge Strings Alternately": "Taking one character from each string gives `a-p-b-q-c-r`.",
    "Move Zeroes": "The non-zero values stay in the order `1,3,12`; both zeroes move behind them.",
    "Is Subsequence": "The letters `a`, `b`, and `c` appear in that order inside `ahbgdc`.",
    "Find Pivot Index": "At index `3`, both the left sum and right sum are `11`.",
    "Unique Number of Occurrences": "The counts are `1 → 3`, `2 → 2`, and `3 → 1`; all counts differ.",
    "Valid Parentheses": "Each opening bracket is closed by the matching type in the correct order.",
    "Reverse Linked List": "Reversing every `next` pointer changes `1 → 2 → 3 → 4 → 5` into `5 → 4 → 3 → 2 → 1`.",
    "Maximum Depth of Binary Tree": "The longest root-to-leaf path contains three nodes, for example `3 → 20 → 15`.",
    "Counting Bits": "The binary values `0, 1, 10, 11, 100, 101` contain `0,1,1,2,1,2` set bits.",
    "Product of Array Except Self": "For index `0`, multiply `2×3×4=24`; repeat while excluding each index.",
    "Group Anagrams": "Words belong together when sorting their letters produces the same key.",
    "Longest Consecutive Sequence": "The longest run is `1,2,3,4`, so its length is `4`.",
    "String Compression": "`aa`, `bb`, and `ccc` become `a2`, `b2`, and `c3`.",
    "Container With Most Water": "The lines at indices `1` and `8` hold `min(8,7) × 7 = 49` units.",
    "Max Number of K-Sum Pairs": "Use pairs `(1,4)` and `(2,3)`; every element is used once.",
    "Longest Substring Without Repeating Characters": "`abc` is a longest substring without a repeated character.",
    "Max Consecutive Ones III": "Flipping two zeroes creates a block of six consecutive ones.",
    "Longest Subarray of 1s After Deleting One": "Delete the zero to join the two blocks of ones into a block of length `3`.",
    "Determine if Two Strings Are Close": "The strings use the same characters with the same set of frequencies.",
    "Equal Row and Column Pairs": "The third row `[2,7,7]` equals the second column `[2,7,7]`.",
    "Decode String": "Repeat `a` three times and `bc` twice: `aaa` + `bcbc`.",
    "Asteroid Collision": "`10` and `-5` collide; the larger asteroid `10` survives.",
    "Daily Temperatures": "After `75`, the next warmer value is `76`, four days later.",
    "Koko Eating Bananas": "At speed `4`, the piles take `1+2+2+3=8` hours; any slower speed takes too long.",
    "Search in Rotated Sorted Array": "The target `0` is stored at index `4`.",
    "Delete the Middle Node of a Linked List": "The list has length `7`, so remove the node at index `3`, whose value is `7`.",
    "Odd Even Linked List": "Odd positions contain `1,3,5`; even positions contain `2,4`.",
    "Maximum Twin Sum of a Linked List": "The twin sums are `5+1=6` and `4+2=6`.",
    "LRU Cache": "Reading key `1` returns `1`. Adding key `3` then evicts key `2`, so its lookup returns `-1`.",
    "Count Good Nodes in Binary Tree": "The good values are the root `3`, the lower-left `3`, `4`, and `5`. None has a larger value earlier on its root path.",
    "Path Sum III": "Three downward paths add to `8`: `5→3`, `5→2→1`, and `-3→11`.",
    "Lowest Common Ancestor of a Binary Tree": "Values `5` and `1` lie in different subtrees of `3`, so `3` is their lowest common ancestor.",
    "Binary Tree Right Side View": "The rightmost visible values at depths `0`, `1`, and `2` are `1`, `3`, and `4`.",
    "Number of Provinces": "Cities `0` and `1` form one province; city `2` forms another.",
    "Rotting Oranges": "The rot spreads one cell per minute and reaches the final fresh orange after four minutes.",
    "Course Schedule": "Take course `0` first, then course `1`; there is no circular dependency.",
    "Kth Largest Element in an Array": "In descending order the values begin `6,5,...`, so the second largest is `5`.",
    "Letter Combinations of a Phone Number": "Digit `2` offers `abc` and digit `3` offers `def`; combine each choice from the first with each from the second.",
    "House Robber": "Rob houses with amounts `1` and `3` for a total of `4`.",
    "Unique Paths": "Every valid path is a different ordering of two down moves and six right moves.",
    "Longest Common Subsequence": "`ace` appears in both strings in order and has length `3`.",
    "Implement Trie": "After inserting `apple`, the full word is found, `app` is not yet a full word, but it is a valid prefix.",
    "Non-overlapping Intervals": "Removing `[1,3]` leaves three intervals that only touch at endpoints.",
    "Online Stock Span": "For price `85`, the six-day sequence `80,60,70,60,75,85` is no greater than `85`.",
    "Trapping Rain Water": "Summing the water held above each position gives `6` units.",
    "Minimum Window Substring": "`BANC` is the shortest part of `s` containing `A`, `B`, and `C`.",
    "Sliding Window Maximum": "The first window `[1,3,-1]` has maximum `3`; continue once per shifted window.",
    "Largest Rectangle in Histogram": "The adjacent bars of heights `5` and `6` support a rectangle of height `5` and width `2`, giving area `10`.",
    "Edit Distance": "Change `horse` to `ros` with three operations: replace `h`, remove the second `r`, and remove `e`.",
}


DIAGRAMS = {
    "Reverse Linked List": "```text\nBefore: 1 → 2 → 3 → 4 → 5 → null\nAfter:  5 → 4 → 3 → 2 → 1 → null\n```",
    "Maximum Depth of Binary Tree": "```text\n      3\n     / \\\n    9  20\n       / \\\n      15  7\n\nLongest path: 3 → 20 → 15 (depth 3)\n```",
    "Valid Parentheses": "```text\nInput:  ( [ ] )\nStack:  ( → ([ → ( → empty\n```",
    "Container With Most Water": "```text\nheight:  1 8 6 2 5 4 8 3 7\n           │             │\n           └─────────────┘  width 7, usable height 7\n```",
    "Delete the Middle Node of a Linked List": "```text\n1 → 3 → 4 → [7] → 1 → 2 → 6\n1 → 3 → 4 ─────→ 1 → 2 → 6\n```",
    "Odd Even Linked List": "```text\nPositions:  1   2   3   4   5\nBefore:     1 → 2 → 3 → 4 → 5\nAfter:      1 → 3 → 5 → 2 → 4\n```",
    "Count Good Nodes in Binary Tree": "```text\n        3 ✓\n       /   \\\n      1     4 ✓\n     /     / \\\n    3 ✓   1   5 ✓\n```",
    "Path Sum III": "```text\nValid target-8 paths include:\n5 → 3       5 → 2 → 1       -3 → 11\n```",
    "Lowest Common Ancestor of a Binary Tree": "```text\n        [3]  ← lowest common ancestor\n        / \\\n       5   1\n```",
    "Binary Tree Right Side View": "```text\n      1  ← visible\n     / \\\n    2   3  ← visible\n     \\   \\\n      5   4  ← visible\n```",
    "Number of Provinces": "```text\nCity 0 ── City 1      City 2\n└── province 1 ──┘    └ province 2\n```",
    "Rotting Oranges": "```text\n2 = rotten, 1 = fresh, 0 = empty\n\nminute 0        minute 1\n2 1 1           2 2 1\n1 1 0     →     2 1 0\n0 1 1           0 1 1\n```",
    "Course Schedule": "```text\n[1,0] means:  course 0 ──→ course 1\nA directed cycle means the schedule is impossible.\n```",
    "Letter Combinations of a Phone Number": "```text\n2: a b c\n3: d e f\n\n   a ─ ad, ae, af\n   b ─ bd, be, bf\n   c ─ cd, ce, cf\n```",
    "Unique Paths": "```text\nS → · → ·\n      ↓   ↓\n· → · → E\n\nOnly moves → and ↓ are allowed.\n```",
    "Non-overlapping Intervals": "```text\n[1────2][2────3][3────4]\n[1──────────3]  ← remove this interval\n```",
    "Trapping Rain Water": "```text\n      █\n  █~~~██~█\n_██~███████_   ~ = trapped water\n```",
    "Sliding Window Maximum": "```text\n[1  3 -1] -3  5  3  6  7  → max 3\n 1 [3 -1 -3]  5  3  6  7  → max 3\n```",
    "Largest Rectangle in Histogram": "```text\n      █\n    █ █\n    █ █\n    █ █   █\n  █ █ █ █ █\n█ █ █ █ █ █\n    └───┘  area = 5 × 2 = 10\n```",
}
