# Generated by Django 5.0.7 on 2026-06-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True),
        ),
    ]
