# Generated by Django 5.0.7 on 2026-06-23 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_resume_parsed_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickRefreshSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Refresh Settings',
                'verbose_name_plural': 'Quick Refresh Settings',
            },
        ),
        migrations.CreateModel(
            name='QuickRefreshNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('plain', 'Plain text'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('python', 'Python'), ('java', 'Java'), ('json', 'JSON'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('markdown', 'Markdown'), ('bash', 'Bash')], default='plain', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_refresh_note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
