# Generated by Django 5.0.7 on 2026-06-24 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_resumeanalysis_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_mode', models.CharField(blank=True, choices=[('manual', 'Manual'), ('chatgpt', 'ChatGPT'), ('claude', 'Claude')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analysis_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Analysis Settings',
                'verbose_name_plural': 'Resume Analysis Settings',
            },
        ),
    ]
