# Generated by Codex on 2026-06-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_resumeanalysissettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuickRefreshNote",
        ),
        migrations.DeleteModel(
            name="QuickRefreshSettings",
        ),
    ]
