# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_remove_quick_refresh"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResumeAnalysisSettings",
            new_name="UserFeatureFlags",
        ),
        migrations.AlterModelTable(
            name="userfeatureflags",
            table="product_user_feature_flags",
        ),
        migrations.AlterModelOptions(
            name="userfeatureflags",
            options={
                "verbose_name": "User Feature Flags",
                "verbose_name_plural": "User Feature Flags",
            },
        ),
        migrations.AlterField(
            model_name="userfeatureflags",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="feature_flags", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="userfeatureflags",
            name="ai_analysis_daily_limit",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userfeatureflags",
            name="ai_analysis_window_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userfeatureflags",
            name="ai_analysis_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
