# Generated by Django 5.0.7 on 2026-07-01 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_user_feature_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeatureflags',
            name='mock_interview_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userfeatureflags',
            name='mock_interview_daily_limit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userfeatureflags',
            name='mock_interview_window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic_source', models.CharField(choices=[('preset', 'Preset'), ('custom', 'Custom')], default='preset', max_length=12)),
                ('topic', models.CharField(max_length=1000)),
                ('level', models.CharField(choices=[('mid', 'Mid-level'), ('senior', 'Senior'), ('staff', 'Staff')], default='senior', max_length=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('transcript_text', models.TextField(blank=True)),
                ('feedback_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_mock_interview_session',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='MockInterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('interviewer', 'Interviewer')], max_length=20)),
                ('text', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='product.mockinterviewsession')),
            ],
            options={
                'db_table': 'product_mock_interview_turn',
                'ordering': ('occurred_at', 'id'),
            },
        ),
    ]
