# Generated by Django 5.0.7 on 2026-07-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_userfeatureflags_mock_interview_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeatureflags',
            name='can_access_coding_platform',
            field=models.BooleanField(default=False),
        ),
    ]
